# Generated by Django 2.1.1 on 2021-09-29 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0002_auto_20210915_1749"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catagory",
            options={"verbose_name_plural": "Catagories"},
        ),
    ]
